version: '2.20'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: cookbook
      POSTGRES_USER: cookbook
      POSTGRES_PASSWORD: cookbook
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres

    volumes:
      - ./tools/adminer-plugins/:/var/www/html/plugins-enabled/
    environment:
      ADMINER_DESIGN: rmsoft

volumes:
  postgres-data:
